spring:
  application:
    name: cloud
  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true
  aws:
    s3:
      bucket: aws-assignment-bucket-sunghyun
