spring:
  config:
    import: "aws-parameterstore:/config/cloud_prod/"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

info:
  team-name: ${team-name}

aws:
  s3:
    bucket: aws-assignment-bucket-sunghyun